name: Run Gradle
description: Sets up Gradle JDKs and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
  java:
    required: true
    description: The JDK version
  token:
    required: false
    description: 'A Github PAT'
runs:
  using: composite
  steps:
    - name: Prepare OpenJDK
      shell: bash
      run: echo "JAVA_VERSION=${{ inputs.java }}" >> $GITHUB_ENV
    - name: Set up JDK ${{ inputs.java }}
      id: setup-jdk
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
      with:
        java-version: ${{ inputs.java }}
        distribution: temurin
    - name: Setup Gradle
      id: setup-gradle
      uses: gradle/actions/setup-gradle@b6816cf21e7970b88479bb3c57d9cbe5cdd4b949 # v3.0.0-rc.1
      with:
        add-job-summary: never
    - name: Run ${{ inputs.arguments }}
      shell: bash
      run: ./gradlew ${{ inputs.arguments }}